version: '3.8'

services:
  web:
    build: .
    command: gunicorn portfolio_project.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
      # CRITICAL: This saves the DB on the server so it survives restarts
      - ./db.sqlite3:/app/db.sqlite3
    expose:
      - 8000
    env_file:
      - .env

  nginx:
    image: nginx:alpine
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  static_volume:
  media_volume: