# Generated by Django 6.0.2 on 2026-02-23 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_project_image_url_alter_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('data_science', 'Data Science'), ('machine_learning', 'Machine Learning'), ('web', 'Web Development'), ('ai', 'AI/LLM')], max_length=50),
        ),
    ]
